import Head from 'next/head'
import React from 'react'

type Props = {}

export default function NextHead({ }: Props) {
    return (
        <Head>
            <title>Sawaup Challenge</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}